### ISSUE TITLE
exception when running json export

### ISSUE THREAD

**Issue by concubicycle** [haccer/twint#115]
Hey, sorry to bug you again. Running json exports seems to not work as it did before. I'm on python 3.6.4. Here's what I ran:

```
PS G:\dev\twinttest\twint> py Twint.py -u vp -o vp.json --json --since 2018-05-05
Traceback (most recent call last):
  File "Twint.py", line 160, in <module>
    main()
  File "Twint.py", line 157, in main
    twint.Search(c)
  File "G:\dev\twinttest\twint\twint\search.py", line 36, in __init__
    loop.run_until_complete(self.main())
  File "C:\Users\Saveliy\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "G:\dev\twinttest\twint\twint\search.py", line 88, in main
    await self.tweets()
  File "G:\dev\twinttest\twint\twint\search.py", line 66, in tweets
    await output.Tweets(tweet, "", self.config, self.conn)
  File "G:\dev\twinttest\twint\twint\output.py", line 232, in Tweets
    writeJSON(Tweet, config.Output)
  File "G:\dev\twinttest\twint\twint\output.py", line 92, in writeJSON
    json_dump(data, json_file)
NameError: name 'json_dump' is not defined
PS G:\dev\twinttest\twint> py --version
Python 3.6.4
```

Running csv exports does still work well.

**Comment by haccer** [comment]
Thanks @concubicycle !

Typo is now fixed.
