### ISSUE TITLE
README.md command not working "twint -u username --user-full"

### ISSUE THREAD

**Issue by RichaMax** [haccer/twint#1244]
I'm currently trying to use Twint to scrape twitter public profile. 
While reading the README and testing a few commands I encountered an error while launching the command `twint -u username --user-full` present in the [readme](https://github.com/twintproject/twint#userlist). The username used here is a user which account is public.

error stack:
```
CRITICAL:root:twint.get:User:'url'
ERROR:root:twint.run:Twint:Lookup:Unexpected exception occurred.
Traceback (most recent call last):
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/output.py", line 177, in Users
    user = User(u)
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'
Traceback (most recent call last):
  File "/home/maxime/.local/bin/twint", line 11, in <module>
    load_entry_point('twint', 'console_scripts', 'twint')()
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/cli.py", line 339, in run_as_command
    main()
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/cli.py", line 326, in main
    run.Lookup(c)
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/run.py", line 386, in Lookup
    run(config)
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/run.py", line 235, in main
    await task
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/run.py", line 270, in run
    await self.Lookup()
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/run.py", line 307, in Lookup
    await get.User(self.config.Username, self.config, db.Conn(self.config.Database))
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/get.py", line 228, in User
    await Users(j_r, config, conn)
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/output.py", line 177, in Users
    user = User(u)
  File "/home/maxime/Documents/work/pocinvestigamax/src/twint/twint/user.py", line 31, in User
    _usr.url = ur['data']['user']['legacy']['url']
KeyError: 'url'

```

I tried this command on my local environment (Ubuntu 20.04) with twint install using `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint` 
An also on a Docker container using a python3.6-alpine container, both ended up falling for this command.

**Comment by Stark1937** [comment]
same question

**Comment by RichaMax** [comment]
@Stark1937 

I currently use the following work around find in one of the issues 

```
import twint
import sys


def get_username_info(file_to_write, username):
    c = twint.Config()
    c.Username = username
    c.Store_json = True
    c.Output = file_to_write
    twint.run.Lookup(c)


if __name__ == "__main__":
    username = sys.argv[1]
    file_to_write = sys.argv[2]
    get_username_info(file_to_write, username)

```

**Comment by uchidaknet** [comment]
@RichaMax @Stark1937 

I fixed `user.py` and it worked for me.

**[The path you installed twint]/twint/user.py line 31**

`_usr.url = ur['data']['user']['legacy']['url']`
↓
`_usr.url = ur['data']['user']['legacy'].get('url')`

Try it out:-)

**Comment by RichaMax** [comment]
Indeed it works like a charm, can't believe I did not think of doing this.

Thanks.
