### ISSUE TITLE
Database write error

### ISSUE THREAD

**Issue by cbjrobertson** [haccer/twint#131]
### Command Ran
```
>>> import twint
>>> c = twint.Config()
>>> c.Database = '/path/to/database.db'
>>> c.Search = '#search_term'
>>> c.Limit = 20
>>> twint.run.Search(c)
```

### Description of Issue
When I run the above commands, the db write operation fails with:
```
Traceback (most recent call last):
  File "<pyshell#49>", line 1, in <module>
    twint.run.Search(c)
  File "/anaconda3/envs/twitter_scrape/lib/python3.6/site-packages/twint/run.py", line 25, in Search
    run(search.Search(config).main())
  File "/anaconda3/envs/twitter_scrape/lib/python3.6/site-packages/twint/run.py", line 5, in run
    get_event_loop().run_until_complete(x)
  File "/anaconda3/envs/twitter_scrape/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/anaconda3/envs/twitter_scrape/lib/python3.6/site-packages/twint/search.py", line 60, in main
    await self.tweets()
  File "/anaconda3/envs/twitter_scrape/lib/python3.6/site-packages/twint/search.py", line 37, in tweets
    await output.Tweets(tweet, "", self.config, self.conn)
  File "/anaconda3/envs/twitter_scrape/lib/python3.6/site-packages/twint/output.py", line 44, in Tweets
    db.tweets(conn, tweet)
  File "/anaconda3/envs/twitter_scrape/lib/python3.6/site-packages/twint/db.py", line 198, in tweets
    cursor.execute('INSERT INTO tweets VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', entry)
sqlite3.OperationalError: table tweets has 17 columns but 16 values were supplied
```

### Environment Details
Im running OSX 10.13.3 and using IDLE to run twint.

**Comment by pielco11** [comment]
The bug is resolved, did you update the pip package?
`pip install --upgrade twint`
