### ISSUE TITLE
[Error] : cannot import name 'CeilTimeout' from 'aiohttp.helpers' , How to fix it?

### ISSUE THREAD

**Issue by nawafAlkhadidi** [haccer/twint#1314]
# Issue Template

### Initial Check

>Make sure you've checked the following:

- [1] Python version is 2.7.18;
- [2] Updated Twint with `pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint`;
- [3] I have searched the issues and there are no duplicates of this issue/question/request.

### Command Ran

`twint -u Nawaf`

### Description of Issue
this error when i run this command Ran (twint -u Nawaf) 
 

> nawafalkh@Nawaf ~ % twint -u Nawaf   
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 5, in <module>
    from twint.cli import run_as_command
  File "/Users/nawafalkhadidi/twint/src/twint/twint/__init__.py", line 14, in <module>
    from . import run
  File "/Users/nawafalkhadidi/twint/src/twint/twint/run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/Users/nawafalkhadidi/twint/src/twint/twint/get.py", line 12, in <module>
    from aiohttp_socks import ProxyConnector, ProxyType
  File "/usr/local/lib/python3.9/site-packages/aiohttp_socks/__init__.py", line 5, in <module>
    from .connector import (
  File "/usr/local/lib/python3.9/site-packages/aiohttp_socks/connector.py", line 8, in <module>
    from aiohttp.helpers import CeilTimeout  # noqa
ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py)

`ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py)`

> 

### Environment Details
> Terminal

**Comment by nawafAlkhadidi** [comment]
#https://github.com/twintproject/twint/issues/1297
