### ISSUE TITLE
error when installing the tool

### ISSUE THREAD

**Issue by ManuelBot59** [haccer/twint#1332]
error when installing the tool, I get this:

┌──(root💀tedd)-[/home/tedd/TOOLS/twint]
└─# twint -s piña                                                       1 ⨯
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 5, in <module>
    from twint.cli import run_as_command
  File "/root/.local/lib/python3.9/site-packages/twint/__init__.py", line 14, in <module>
    from . import run
  File "/root/.local/lib/python3.9/site-packages/twint/run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/root/.local/lib/python3.9/site-packages/twint/get.py", line 12, in <module>
    from aiohttp_socks import ProxyConnector, ProxyType
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_socks/__init__.py", line 5, in <module>
    from .connector import (
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_socks/connector.py", line 8, in <module>
    from aiohttp.helpers import CeilTimeout  # noqa
ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/usr/lib/python3/dist-packages/aiohttp/helpers.py)

**Comment by hxyro** [comment]
Try replacing aiohttp with aiohttp==3.7.0 in the first line of requeriments.txt

**Comment by exiett** [comment]
> 

This worked just fine. Thanks.

**Comment by be-lka** [comment]
> Try replacing aiohttp with aiohttp==3.7.0 in the first line of requeriments.txt

This worked just fine. Thank you.
