### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ManuelBot59** [haccer/twint#1337]
└─# twint -u canalN_                                                                                                          1 ⨯
Traceback (most recent call last):
  File "/usr/local/bin/twint", line 5, in <module>
    from twint.cli import run_as_command
  File "/root/.local/lib/python3.9/site-packages/twint/__init__.py", line 14, in <module>
    from . import run
  File "/root/.local/lib/python3.9/site-packages/twint/run.py", line 4, in <module>
    from . import datelock, feed, get, output, verbose, storage
  File "/root/.local/lib/python3.9/site-packages/twint/get.py", line 12, in <module>
    from aiohttp_socks import ProxyConnector, ProxyType
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_socks/__init__.py", line 5, in <module>
    from .connector import (
  File "/usr/local/lib/python3.9/dist-packages/aiohttp_socks/connector.py", line 8, in <module>
    from aiohttp.helpers import CeilTimeout  # noqa
ImportError: cannot import name 'CeilTimeout' from 'aiohttp.helpers' (/usr/lib/python3/dist-packages/aiohttp/helpers.py)

**Comment by LaurenceJJones** [comment]
You opened two issues based on the same error see reply to your original? https://github.com/twintproject/twint/issues/1332

**Comment by LaurenceJJones** [comment]
Also if you used the search and search for keyword like CeilTimeout you find the fix https://github.com/twintproject/twint/issues/1297#issuecomment-958105596
