### ISSUE TITLE
MaxRetryError

### ISSUE THREAD

**Issue by wjjwztc** [haccer/twint#1359]
D:\nft\twint>twint -u ****
WARNING:root:Error retrieving https://twitter.com/: ProxyError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out')))")), retrying
WARNING:root:Error retrieving https://twitter.com/: ProxyError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out')))")), retrying
WARNING:root:Error retrieving https://twitter.com/: ProxyError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out')))")), retrying
WARNING:root:Error retrieving https://twitter.com/: ProxyError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out')))")), retrying
WARNING:root:Error retrieving https://twitter.com/: ProxyError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out')))")), retrying
ERROR:root:Error retrieving https://twitter.com/: ProxyError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out')))"))
CRITICAL:root:6 requests to https://twitter.com failed, giving up.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\twint-script.py", line 33, in <module>
    sys.exit(load_entry_point('twint==2.1.21', 'console_scripts', 'twint')())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\twint\cli.py", line 339, in run_as_command
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\twint\cli.py", line 330, in main
    run.Search(c)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\twint\run.py", line 410, in Search
    run(config, callback)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\twint\run.py", line 329, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\twint\run.py", line 36, in __init__
    self.token.refresh()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\twint\token.py", line 62, in refresh
    res = self._request()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\twint\token.py", line 58, in _request
    raise RefreshTokenException(msg)
twint.token.RefreshTokenException: 6 requests to https://twitter.com failed, giving up.

**Comment by snail-tyy** [comment]
WOW now I face the problem as you,but I don't know how to fix it.

**Comment by shizia** [comment]
> WOW now I face the problem as you,but I don't know how to fix it.

Me too.

**Comment by theCreativitist** [comment]
I had the same problem.
fix? changing the proxy.
apparently the proxy was blocked by twitter servers.
