### ISSUE TITLE
CRITICAL Error

### ISSUE THREAD

**Issue by arch3angel** [haccer/twint#1378]
### Environment Details
- Operating System [ Ubuntu 20.04 ]
- Python Version [ 3.8.10 ]
- ELK Stack Version [ 7.17.1 ]
- Updated Twint [ Attempted ]
- Search Attempted [ Yes ]

Initial Twint Install Done Via:
```sudo pip3 install twint```

Attempted Twint update as requested and received the following:
```
|username@servername|20220322|20:13:54 EDT(-0400)|~$ sudo pip3 install --user --upgrade -e git+https://github.com/twintproject/twint.git@origin/master#egg=twint
Obtaining twint from git+https://github.com/twintproject/twint.git@origin/master#egg=twint
  Cloning https://github.com/twintproject/twint.git (to revision origin/master) to ./src/twint
  Running command git clone -q https://github.com/twintproject/twint.git /home/username/src/twint
  WARNING: Did not find branch or tag 'origin/master', assuming revision or ref.
  Running command git checkout -q origin/master
Requirement already satisfied, skipping upgrade: aiodns in /usr/local/lib/python3.8/dist-packages (from twint) (3.0.0)
Requirement already satisfied, skipping upgrade: aiohttp in /usr/local/lib/python3.8/dist-packages (from twint) (3.8.1)
Requirement already satisfied, skipping upgrade: aiohttp_socks in /usr/local/lib/python3.8/dist-packages (from twint) (0.7.1)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from twint) (4.10.0)
Requirement already satisfied, skipping upgrade: cchardet in /usr/local/lib/python3.8/dist-packages (from twint) (2.1.7)
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Requirement already satisfied, skipping upgrade: elasticsearch in /usr/local/lib/python3.8/dist-packages (from twint) (8.1.1)
Requirement already satisfied, skipping upgrade: fake-useragent in /usr/local/lib/python3.8/dist-packages (from twint) (0.1.11)
Requirement already satisfied, skipping upgrade: geopy in /usr/local/lib/python3.8/dist-packages (from twint) (2.2.0)
Requirement already satisfied, skipping upgrade: googletransx in /usr/local/lib/python3.8/dist-packages (from twint) (2.4.2)
Requirement already satisfied, skipping upgrade: pandas in /usr/local/lib/python3.8/dist-packages (from twint) (1.4.1)
Requirement already satisfied, skipping upgrade: pysocks in /usr/local/lib/python3.8/dist-packages (from twint) (1.7.1)
Requirement already satisfied, skipping upgrade: schedule in /usr/local/lib/python3.8/dist-packages (from twint) (1.1.0)
Requirement already satisfied, skipping upgrade: pycares>=4.0.0 in /usr/local/lib/python3.8/dist-packages (from aiodns->twint) (4.1.2)
Requirement already satisfied, skipping upgrade: aiosignal>=1.1.2 in /usr/local/lib/python3.8/dist-packages (from aiohttp->twint) (1.2.0)
Requirement already satisfied, skipping upgrade: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp->twint) (6.0.2)
Requirement already satisfied, skipping upgrade: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->twint) (1.7.2)
Requirement already satisfied, skipping upgrade: frozenlist>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from aiohttp->twint) (1.3.0)
Requirement already satisfied, skipping upgrade: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp->twint) (19.3.0)
Requirement already satisfied, skipping upgrade: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.8/dist-packages (from aiohttp->twint) (4.0.2)
Requirement already satisfied, skipping upgrade: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->twint) (2.0.12)
Requirement already satisfied, skipping upgrade: python-socks[asyncio]<3.0.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp_socks->twint) (2.0.3)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in /usr/local/lib/python3.8/dist-packages (from beautifulsoup4->twint) (2.3.1)
Requirement already satisfied, skipping upgrade: elastic-transport<9,>=8 in /usr/local/lib/python3.8/dist-packages (from elasticsearch->twint) (8.1.0)
Requirement already satisfied, skipping upgrade: geographiclib<2,>=1.49 in /usr/local/lib/python3.8/dist-packages (from geopy->twint) (1.52)
Requirement already satisfied, skipping upgrade: requests in /usr/lib/python3/dist-packages (from googletransx->twint) (2.22.0)
Requirement already satisfied, skipping upgrade: numpy>=1.18.5; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas->twint) (1.22.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.8.1 in /usr/local/lib/python3.8/dist-packages (from pandas->twint) (2.8.2)
Requirement already satisfied, skipping upgrade: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas->twint) (2022.1)
Requirement already satisfied, skipping upgrade: cffi>=1.5.0 in /usr/local/lib/python3.8/dist-packages (from pycares>=4.0.0->aiodns->twint) (1.15.0)
Requirement already satisfied, skipping upgrade: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp->twint) (2.8)
Requirement already satisfied, skipping upgrade: certifi in /usr/lib/python3/dist-packages (from elastic-transport<9,>=8->elasticsearch->twint) (2019.11.28)
Requirement already satisfied, skipping upgrade: urllib3<2,>=1.26.2 in /usr/local/lib/python3.8/dist-packages (from elastic-transport<9,>=8->elasticsearch->twint) (1.26.9)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas->twint) (1.14.0)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python3.8/dist-packages (from cffi>=1.5.0->pycares>=4.0.0->aiodns->twint) (2.21)
Installing collected packages: dataclasses, twint
  Attempting uninstall: twint
    Found existing installation: twint 2.1.20
    Uninstalling twint-2.1.20:
      Successfully uninstalled twint-2.1.20
  Running setup.py develop for twint
Successfully installed dataclasses-0.6 twint
|username@servername|20220322|20:15:00 EDT(-0400)|~$
```

### Command Ran
```|username@servername|20220322|20:08:39 EDT(-0400)|~$ sudo twint -s pineapple```

### Output
```
|username@servername|20220322|20:08:39 EDT(-0400)|~$ sudo twint -s pineapple
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 15 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 15 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 27.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 64.0 secs
CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)
sleeping for 125.0 secs
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 65, in Feed
    self.feed, self.init = feed.Json(response)
  File "/usr/local/lib/python3.8/dist-packages/twint/feed.py", line 42, in Json
    json_response = loads(response)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/twint", line 8, in <module>
    sys.exit(run_as_command())
  File "/usr/local/lib/python3.8/dist-packages/twint/cli.py", line 305, in run_as_command
    main()
  File "/usr/local/lib/python3.8/dist-packages/twint/cli.py", line 297, in main
    run.Search(c)
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 327, in Search
    run(config, callback)
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 226, in run
    get_event_loop().run_until_complete(Twint(config).main(callback))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 199, in run
    await self.tweets()
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 137, in tweets
    await self.Feed()
  File "/usr/local/lib/python3.8/dist-packages/twint/run.py", line 98, in Feed
    time.sleep(delay)
KeyboardInterrupt

|username@servername|20220322|20:13:44 EDT(-0400)|~$
``` 

### Description of Issue
This has happened on my previous DEV box and I did a complete fresh install on my PROD box only to have the same thing happen.  It will sit there repeating the CRITICAL warning and "sleeping for" lines until I manual CTRL-C the operation.  My DEV box has been working absolutely perfect for weeks until recently.  Then stopped responding resulting in these errors

**Comment by arch3angel** [comment]
Issue Resolved:

https://kb.objectrocket.com/elasticsearch/how-to-fix-the-requestsdependencywarning-elasticsearch-with-python-import-error-453
