### ISSUE TITLE
[Error] Failing before limit

### ISSUE THREAD

**Issue by TylerSchnoebelen** [haccer/twint#71]
I've run Twint successfully a lot with no issues (thanks! it's great!), but starting last night, a number of of attempts have run into problems. I'm wondering what you make of these errors. I do have Python 3.6.5 and the latest version of Twint. I'm running on Mac OS High Sierra 10.13.4. 

python3 twint.py -u NickKristof -o NickKristof_m_lib_twint.csv --csv
(runs for a  few hundred tweets and then...)

Traceback (most recent call last):
  File "twint.py", line 193, in fetch
    async with session.get(url) as response:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 783, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 333, in _request
    await resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 695, in start
    (message, payload) = await self._protocol.read()
  File "/usr/local/lib/python3.6/site-packages/aiohttp/streams.py", line 533, in read
    await self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twint.py", line 771, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "twint.py", line 689, in main
    feed, init, count = await getTweets(init)
  File "twint.py", line 510, in getTweets
    tweets, init = await getFeed(init)
  File "twint.py", line 291, in getFeed
    response = await fetch(session, await getUrl(init))
  File "twint.py", line 194, in fetch
    return await response.text()
  File "/usr/local/lib/python3.6/site-packages/async_timeout/__init__.py", line 38, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.6/site-packages/async_timeout/__init__.py", line 83, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

**Comment by haccer** [comment]
That just means the connection to Twitter took too long (more than 30 seconds) i.e timed out
