### ISSUE TITLE
problem insertind data in SQlite3

### ISSUE THREAD

**Issue by Nestor75** [haccer/twint#80]
### Initial Check 
Make sure you've checked the following.

- [x] Python version is 3.5 or higher.
- [x] Using the latest version of Twint.

### Command
Please provide the exact command ran including the username/search so I may reproduce the issue.
python twint.py -s valencia --since 2018-04-01 --until 2018-04-27  --count -l es --limit 20 --database twitterdata

### Description of Issue
I just created the database so there is no tables already created
I executed the command , it finished succesfully but nothing is created in the DB. 
in the files DB.py the codes for tables creation are commented. I descommented them and I got this error:
Traceback (most recent call last):
  File "twint.py", line 16, in <module>
    import twint
  File "/media/sf_virtualboxshare/twint-master_v2/twint/__init__.py", line 1, in <module>
    from .followers import Followers
  File "/media/sf_virtualboxshare/twint-master_v2/twint/followers.py", line 1, in <module>
    from . import feed, get, db, output
  File "/media/sf_virtualboxshare/twint-master_v2/twint/get.py", line 1, in <module>
    from . import output
  File "/media/sf_virtualboxshare/twint-master_v2/twint/output.py", line 3, in <module>
    from . import db, elasticsearch
  File "/media/sf_virtualboxshare/twint-master_v2/twint/db.py", line 8
    table_tweets = 
                  ^
SyntaxError: invalid syntax

=======
Do I have to create the tables before hand?

thank you very much for your help

### OS Details
Using Windows, Linux? Linux  What OS version? ubuntu 16

**Comment by Nestor75** [comment]
I leaved the file db.py like it was , I created the tables manually and I executed the command successfully but no record has  been inserted in the DB :(

**Comment by Nestor75** [comment]
my fault, the system works perfect. 1st I did not put the correct db path, 2nd I put it in a VB shared folder and then it gave a I/O disk error. IT WORKS!!!!!! 
many thanks for all
