### ISSUE TITLE
Missing something

### ISSUE THREAD

**Issue by blind0wl** [haccer/twint#83]
Hey there,

I've run this absolutely fine in Arch and have been trying to use it on another machine using debian.  I'm getting this error:
```python
Traceback (most recent call last):
  File "twint.py", line 117, in <module>
    main()
  File "twint.py", line 114, in main
    twint.Search(c)
  File "/home/rust/twint/twint/search.py", line 38, in __init__
    loop.run_until_complete(self.main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/rust/twint/twint/search.py", line 96, in main
    await self.tweets()
  File "/home/rust/twint/twint/search.py", line 73, in tweets
    await output.Tweets(tweet, "", self.config, self.conn)
  File "/home/rust/twint/twint/output.py", line 205, in Tweets
    print(output)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 155-156: ordinal not in range(128)
```
I've ran the pips3 requirements and they seem fine...from what I can gather its a locale issue, but nothing I've done at this stage seems to work.

Sorry to keep hassling you all...scratching my head now

**Comment by pielco11** [comment]
Does Twint work properly with the same tweet in Arch? If not, it could be a problem with encoding, try adding `.encode('utf-8').strip()` at the end of `output`... so that at line 205 in `twint/output.py` you have `print(output.encode('utf-8').strip())`

**Comment by haccer** [comment]
What's your locale?

**Comment by haccer** [comment]
I would suggest looking at issue #24 - someone on Debian Stretch had a misconfigured locale wherein one of the variables (LC_CTYPE) were set to `UTF-8` and not `en-GB.UTF-8`.. Hope that helps.

**Comment by blind0wl** [comment]
Thank you, I ran:
`dpkg-reconfigure locales`
and just reset my locales on the system and it all started working.

Thanks again
