### ISSUE TITLE
asyncio.TimeoutError

### ISSUE THREAD

**Issue by nbreide** [haccer/twint#88]
### Command
python3 twint.py -u realDonaldTrump -o DT.json --json

### Description of Issue
Timeout error kills the crawl.  Python Traceback provided below: 

Traceback (most recent call last):
  File "/Users/nbreide/twint/twint/get.py", line 77, in Response
    async with session.get(url) as response:
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 783, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 320, in _request
    traces=traces
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 418, in connect
    traces=traces
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 733, in _create_connection
    traces=traces
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 838, in _create_direct_connection
    req=req, client_error=client_error)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/connector.py", line 797, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 765, in create_connection
    yield from self.sock_connect(sock, address)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "twint.py", line 117, in <module>
    main()
  File "twint.py", line 114, in main
    twint.Search(c)
  File "/Users/nbreide/twint/twint/search.py", line 38, in __init__
    loop.run_until_complete(self.main())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/nbreide/twint/twint/search.py", line 96, in main
    await self.tweets()
  File "/Users/nbreide/twint/twint/search.py", line 54, in tweets
    await self.Feed()
  File "/Users/nbreide/twint/twint/search.py", line 43, in Feed
    response = await get.Response(session, await get.Url(self.config, self.init).search())
  File "/Users/nbreide/twint/twint/get.py", line 78, in Response
    return await response.text()
  File "/usr/local/lib/python3.6/site-packages/async_timeout/__init__.py", line 38, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.6/site-packages/async_timeout/__init__.py", line 83, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError

### OS Details
macOS High Sierra, version 10.13.3
python version 3.6.5

**Comment by pielco11** [comment]
It seems to be a connection problem, does the problem occur over time?

**Comment by haccer** [comment]
Yeah this means you had trouble connecting to Twitter, the current timeout is set to 30 seconds.

**Comment by ElLorans** [comment]
What can I do if I regularly face this error after a couple of hours running twint?
